name: jaxgcrl
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scipy=1.12.0
  - scikit-image=0.22.0
  - dm-haiku=0.0.11
  - six=1.16.0
  - statsmodels=0.14.1
  - pyinstrument=4.6
  - matplotlib=3.8
  - pytest=7.4.4
  - wandb
  - cuda-nvcc=12.8
  - cudnn=8.9
  - flax
  - chex
  - pip
  - pip:
    - brax==0.12.1
    - mujoco==3.2.7
    - mujoco-mjx==3.2.7
    - stack-data==0.6.3
    - nvidia-cufft-cu12==11.2.0.44
    - nvidia-cusolver-cu12==11.6.0.99
    - nvidia-cuda-cupti-cu12==12.4.99
    - tyro==0.9.16
    - wandb_osh==1.2.2
    - jax==0.4.25
    - jaxlib==0.4.25+cuda12.cudnn89
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - scikit-learn==1.6.1